# Generated by Django 4.2.3 on 2023-07-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GidaIhtiyaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('human_count', models.IntegerField()),
                ('address', models.TextField()),
                ('address_description', models.TextField()),
                ('physical_info', models.CharField(max_length=10)),
                ('tweet_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
