# Generated by Django 4.2.3 on 2023-07-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_gidaihtiyaci_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gidaihtiyaci',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
